# apiVersion: v1
# kind: Service
# metadata:
#   name: hostel-management-service
# spec:
#   selector:
#     app: hostel-management
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 5000
#   type: LoadBalancer

apiVersion: v1
kind: Service
metadata:
  name: hostel-management-service
  labels:
    app: hostel-management
spec:
  type: LoadBalancer
  selector:
    app: hostel-management
  ports:
    - protocol: TCP
      port: 80          # Public port
      targetPort: 5000  # Flask container port
